[package]
name = "eth2-libp2p"
version = "0.2.0"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"

[dependencies]
hex = "0.4.2"
types = { path =  "../../eth2/types" }
hashset_delay = { path = "../../eth2/utils/hashset_delay" }
eth2_ssz_types = { path =  "../../eth2/utils/ssz_types" }
serde = { version = "1.0.106", features = ["derive"] }
serde_derive = "1.0.106"
eth2_ssz = "0.1.2"
eth2_ssz_derive = "0.1.0"
slog = { version = "2.5.2", features = ["max_level_trace"] }
version = { path = "../version" }
tokio = { version = "0.2.20", features = ["time"] }
futures = "0.3.4"
error-chain = "0.12.2"
dirs = "2.0.2"
fnv = "1.0.6"
unsigned-varint = { git = "https://github.com/sigp/unsigned-varint", branch = "latest-codecs", features = ["futures-codec"] }
lazy_static = "1.4.0"
lighthouse_metrics = { path = "../../eth2/utils/lighthouse_metrics" }
smallvec = "1.4.0"
lru = "0.4.3"
parking_lot = "0.10.2"
sha2 = "0.8.1"
base64 = "0.12.0"
snap = "1.0.0"
void = "1.0.2"
tokio-io-timeout = "0.4.0"
discv5 = { git = "https://github.com/sigp/discv5", rev="6dfb477d4554be3133135e52a5886778c05813fe" }
tiny-keccak = "2.0.2"
futures_codec = "0.4.0"
serde_millis = "0.1.1"

[dependencies.libp2p]
version = "0.18.1"
default-features = false
features = ["websocket", "ping", "identify", "mplex", "yamux", "noise", "secio", "gossipsub", "tcp", "dns"]


[dev-dependencies]
tokio = { version = "0.2.20", features = ["full"] }
slog-stdlog = "4.0.0"
slog-term = "2.5.0"
slog-async = "2.5.0"
tempdir = "0.3.7"
