name: docker

on:
  push:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Dockerhub login
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
            echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Build Docker Buildx
        run: |
            git clone git://github.com/docker/buildx && cd buildx && make install

      - name: Create Docker Builder
        run: |
            docker buildx create --use --name build --node build --driver-opt network=host

      - name: Build dockerfile (with push)
        run: |
            docker buildx build \
                --platform=linux/amd64,linux/arm64 \
                --output "type=image,push=true" \
                --file ../Dockerfile . \
                --tag seananderson33/lighthouse:latest
