name: docker

on:
    push:
        branches:
            - master

jobs:
    build-docker-image:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@master

            -   name: Dockerhub login
                env:
                    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                run: |
                    echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

            -   name: Build Docker Buildx
                run: |
                    export DOCKER_BUILDKIT=1;
                    docker build --platform=local -o . git://github.com/docker/buildx;
                    mkdir -p ~/.docker/cli-plugins;
                    mv buildx ~/.docker/cli-plugins/docker-buildx;

            -   name: Create Docker Builder
                env:
                    DOCKER_ARM_HOST: ${{ secrets.DOCKER_ARM_HOST }}
                run: |
                    docker buildx create --use --name cross-builder;

            -   name: Build dockerfile (with push)
                run: |
                    docker buildx build \
                        --build-arg PORTABLE=true \
                        --push -t seananderson33/lighthouse:latest \
                        --platform=linux/amd64,linux/arm64 .
