name: docker

on:
    push:
        branches:
            - master

jobs:
    build-docker-arm64:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: Dockerhub login
              env:
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: |
                  echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: Cross build lighthouse binary
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --manifest-path lighthouse/Cargo.toml --target aarch64-unknown-linux-gnu --features portable
            - name: Cross build lcli binary
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --manifest-path lcli/Cargo.toml --target aarch64-unknown-linux-gnu --features portable
            - name: Move cross-built ARM binaries into Docker scope
              run: |
                  mkdir ./bin;
                  mv ./target/aarch64-unknown-linux-gnu/release/lighthouse ./bin;
                  mv ./target/aarch64-unknown-linux-gnu/release/lcli ./bin;
            - name: Build Docker Buildx
              run: |
                  export DOCKER_BUILDKIT=1;
                  docker build --platform=local -o . git://github.com/docker/buildx;
                  mkdir -p ~/.docker/cli-plugins;
                  mv buildx ~/.docker/cli-plugins/docker-buildx;
            - name: Create Docker Builder
              run: |
                  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes;
                  docker context create builder;
                  docker buildx create --use --name lighthouse builder;
            - name: Build ARM64 dockerfile (with push)
              run: |
                  docker buildx build \
                      --platform=linux/arm64 \
                      --output "type=image,push=true" \
                      --file ./Dockerfile.cross . \
                      --tag seananderson33/lighthouse:latest-arm64
    build-docker-amd64:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: Dockerhub login
              env:
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: |
                  echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
            - name: Build AMD64 dockerfile (with push)
              run: |
                  docker build \
                      --build-arg PORTABLE=true \
                      --output "type=image,push=true" \
                      --file ./Dockerfile . \
                      --tag seananderson33/lighthouse:latest-amd64
    build-docker-multiarch:
        runs-on: ubuntu-18.04
        needs: [build-docker-arm64, build-docker-amd64]
        steps:
            - uses: actions/checkout@v1
            - name: Create and push multiarch manifest
              run: |
                  docker manifest create seananderson33/lighthouse:latest \
                      --amend seananderson33/lighthouse:latest-amd64 \
                      --amend seananderson33/lighthouse:latest-arm64;
                  docker manifest push seananderson33/lighthouse:latest;