name: docker

on:
    push:
        branches:
            - unstable
            - stable

env:
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    BRANCH_NAME: ${GITHUB_REF#refs/heads/}
    IMAGE_NAME: seananderson33/lighthouse

jobs:
    build-docker-arm64:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: Dockerhub login
              run: |
                  echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: Cross build lighthouse binary
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --manifest-path lighthouse/Cargo.toml --target aarch64-unknown-linux-gnu --features portable
            - name: Cross build lcli binary
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --manifest-path lcli/Cargo.toml --target aarch64-unknown-linux-gnu --features portable
            - name: Move cross-built ARM binaries into Docker scope
              run: |
                  mkdir ./bin;
                  mv ./target/aarch64-unknown-linux-gnu/release/lighthouse ./bin;
                  mv ./target/aarch64-unknown-linux-gnu/release/lcli ./bin;
            - name: Build Docker Buildx
              run: |
                  export DOCKER_BUILDKIT=1;
                  docker build --platform=local -o . git://github.com/docker/buildx;
                  mkdir -p ~/.docker/cli-plugins;
                  mv buildx ~/.docker/cli-plugins/docker-buildx;
            - name: Create Docker Builder
              run: |
                  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes;
                  docker context create builder;
                  docker buildx create --use --name lighthouse builder;
            - name: Set Env
              if: ${{ ${BRANCH_NAME} == 'unstable' }}
              run: |
                  echo "TAG_SUFFIX=-unstable" >> $GITHUB_ENV;
            - name: Build ARM64 dockerfile (with push)
              run: |
                  docker buildx build \
                      --platform=linux/arm64 \
                      --output "type=image,push=true" \
                      --file ./Dockerfile.cross . \
                      --tag ${IMAGE_NAME}:latest-arm64${TAG_SUFFIX}}
    build-docker-amd64:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: Dockerhub login
              run: |
                  echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
            - name: Set Env
              if: ${{ ${BRANCH_NAME} == 'unstable' }}
              run: |
                  echo "TAG_SUFFIX=-unstable" >> $GITHUB_ENV;
            - name: Build AMD64 dockerfile (with push)
              run: |
                  docker build \
                      --build-arg PORTABLE=true \
                      --output "type=image,push=true" \
                      --file ./Dockerfile . \
                      --tag ${IMAGE_NAME}:latest-amd64${TAG_SUFFIX}
    build-docker-multiarch:
        runs-on: ubuntu-18.04
        needs: [build-docker-arm64, build-docker-amd64]
        steps:
            - name: Dockerhub login
              run: |
                  echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
            - name: Set Env
              if: ${{ ${BRANCH_NAME} == 'unstable' }}
              run: |
                echo "TAG_SUFFIX=-unstable" >> $GITHUB_ENV;
            - name: Create and push multiarch manifest
              # We need to enable experimental docker features in order to use `docker manifest`
              run: |
                  export DOCKER_CLI_EXPERIMENTAL=enabled;
                  docker manifest create ${IMAGE_NAME}:latest${TAG_SUFFIX} \
                      --amend ${IMAGE_NAME}:latest-arm64${TAG_SUFFIX} \
                      --amend ${IMAGE_NAME}:latest-amd64${TAG_SUFFIX};
                  docker manifest push ${IMAGE_NAME}:latest${TAG_SUFFIX}